from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.responses import FileResponse
from app.models.schemas import PlannerRequest
from app.core.route_planner import plan_routes_from_safe_airspace
import tempfile
import json
import os

app = FastAPI(title="DJI Route Planner API")

def remove_file(path: str):
    try:
        if os.path.exists(path):
            os.remove(path)
    except Exception:
        pass

@app.post("/api/v1/planner/generate_kmz")
def generate_kmz(request: PlannerRequest, background_tasks: BackgroundTasks):
    try:
        # Create temporary files for input and output
        with tempfile.NamedTemporaryFile(delete=False, suffix=".geojson", mode="w") as tmp_in:
            if isinstance(request.boundary_geojson, str):
                tmp_in.write(request.boundary_geojson)
            else:
                json.dump(request.boundary_geojson, tmp_in)
            input_file = tmp_in.name

        with tempfile.NamedTemporaryFile(delete=False, suffix=".kmz") as tmp_out:
            output_file = tmp_out.name

        camera_info = {
            "fov_horizontal_deg": request.fov_h,
            "fov_vertical_deg": request.fov_v
        }

        # Call the core routing logic
        plan_routes_from_safe_airspace(
            safe_airspace_file=input_file,
            flight_alt_agl=request.agl,
            flight_speed=request.speed,
            camera_info=camera_info,
            forward_overlap=request.overlap_f,
            side_overlap=request.overlap_s,
            output_kmz=output_file,
            waypoint_mode=request.waypoint_mode,
            drone_enum=request.drone_enum,
            payload_enum=request.payload_enum
        )

        # Ensure the output file exists
        if not os.path.exists(output_file):
            raise HTTPException(status_code=500, detail="Failed to generate KMZ file")

        # Clean up input file right away, output file after sending
        remove_file(input_file)

        # Cleanup tasks after response is sent
        background_tasks.add_task(remove_file, output_file)
        # Also clean up the geojson generated by route_planner if it exists
        geojson_out = output_file.replace('.kmz', '_waypoints.geojson')
        background_tasks.add_task(remove_file, geojson_out)

        return FileResponse(
            path=output_file,
            media_type="application/vnd.google-earth.kmz",
            filename="flight_routes.kmz"
        )

    except Exception as e:
        # Cleanup on failure
        if 'input_file' in locals():
            remove_file(input_file)
        if 'output_file' in locals():
            remove_file(output_file)
        raise HTTPException(status_code=500, detail=str(e))
